# -*- coding: utf-8 -*-
"""inference

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WnUME0aEvTFsk0jWcDGviX1pX_QUVH1V
"""

import cv2
import numpy as np
import joblib
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
MODELS_DIR = BASE_DIR / "models"

def load_models():
    line_model = joblib.load(MODELS_DIR / "line_model.pkl")
    dot_model = joblib.load(MODELS_DIR / "dot_model.pkl")
    return line_model, dot_model

def red_mask_from_bgr(img):
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

    lower1 = np.array([0, 70, 50])
    upper1 = np.array([10, 255, 255])

    lower2 = np.array([170, 70, 50])
    upper2 = np.array([180, 255, 255])

    mask1 = cv2.inRange(hsv, lower1, upper1)
    mask2 = cv2.inRange(hsv, lower2, upper2)
    mask = cv2.bitwise_or(mask1, mask2)

    kernel = np.ones((3, 3), np.uint8)
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel)
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel)

    return mask

def detect_red_circles_from_bgr(img_bgr):
    img = cv2.resize(img_bgr, (800, 600))
    mask = red_mask_from_bgr(img)

    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5, 5))
    mask_thick = cv2.dilate(mask, kernel, iterations=1)
    blur = cv2.GaussianBlur(mask_thick, (9, 9), 2)

    circles = cv2.HoughCircles(
        blur,
        cv2.HOUGH_GRADIENT,
        dp=1.2,
        minDist=35,
        param1=100,
        param2=14,
        minRadius=10,
        maxRadius=45
    )

    circles_info = []

    if circles is not None:
        circles = np.round(circles[0]).astype(int)

        kept = []
        for (cx, cy, r) in circles:
            keep = True
            for (kx, ky, kr) in kept:
                dist = np.sqrt((cx - kx) ** 2 + (cy - ky) ** 2)
                if dist < 0.6 * min(r, kr):
                    keep = False
                    break
            if keep:
                kept.append((cx, cy, r))

        for (cx, cy, r) in kept:
            if r < 8:
                continue

            full_mask = np.zeros(mask.shape, dtype=np.uint8)
            cv2.circle(full_mask, (cx, cy), r, 255, -1)

            inner_mask = np.zeros(mask.shape, dtype=np.uint8)
            cv2.circle(inner_mask, (cx, cy), int(r * 0.60), 255, -1)

            ring_mask = cv2.subtract(full_mask, inner_mask)

            ring_pixels = mask[ring_mask > 0]
            fill_pixels = mask[inner_mask > 0]

            if len(ring_pixels) == 0 or len(fill_pixels) == 0:
                continue

            ring_red_ratio = ring_pixels.mean() / 255.0
            fill_red_ratio = fill_pixels.mean() / 255.0

            if ring_red_ratio > 0.10 or fill_red_ratio > 0.18:
                is_filled = fill_red_ratio > 0.35
                circles_info.append({
                    "x": int(cx),
                    "y": int(cy),
                    "r": int(r),
                    "is_filled": bool(is_filled)
                })

    return img, mask, circles_info

def extract_line_strip_features_from_bgr(img_bgr):
    img = cv2.resize(img_bgr, (300, 500))
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    h, w = gray.shape
    x1, x2 = int(w * 0.30), int(w * 0.65)
    y1, y2 = int(h * 0.05), int(h * 0.95)
    search = gray[y1:y2, x1:x2]

    line_y1, line_y2 = int(search.shape[0] * 0.05), int(search.shape[0] * 0.55)
    line_roi = search[line_y1:line_y2, :]

    blur = cv2.GaussianBlur(line_roi, (5, 5), 0)
    _, thresh = cv2.threshold(
        blur, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU
    )

    kernel = np.ones((3, 3), np.uint8)
    thresh = cv2.morphologyEx(thresh, cv2.MORPH_OPEN, kernel)

    row_sums = thresh.sum(axis=1).astype(np.float32)
    peak_idx_local = np.argmax(row_sums)
    line_y_global = peak_idx_local + line_y1

    col_profile = search.mean(axis=0)
    strip_center = np.argmin(col_profile)

    band_half = 20
    sx1 = max(0, strip_center - band_half)
    sx2 = min(search.shape[1], strip_center + band_half)
    strip_band = search[:, sx1:sx2]

    vertical_profile = strip_band.mean(axis=1)
    thresh_strip = vertical_profile.mean()
    strip_rows = np.where(vertical_profile < thresh_strip)[0]

    if len(strip_rows) < 10:
        strip_top = int(search.shape[0] * 0.10)
        strip_bottom = int(search.shape[0] * 0.90)
    else:
        strip_top = strip_rows[0]
        strip_bottom = strip_rows[-1]

    strip_height = max(strip_bottom - strip_top, 1)
    relative_line_y = (line_y_global - strip_top) / strip_height

    return np.array([[relative_line_y]], dtype=np.float32)

def extract_dot_strip_features_from_bgr(img_bgr):
    _, _, circles_info = detect_red_circles_from_bgr(img_bgr)

    filled_count = sum(1 for c in circles_info if c["is_filled"])
    outline_count = sum(1 for c in circles_info if not c["is_filled"])
    total_count = len(circles_info)
    filled_ratio = filled_count / max(total_count, 1)

    return np.array([[filled_count, outline_count, total_count, filled_ratio]], dtype=np.float32)

def detect_strip_type_rule_based_from_bgr(img_bgr):
    _, _, circles_info = detect_red_circles_from_bgr(img_bgr)
    circle_count = len(circles_info)

    if circle_count >= 4:
        return "dot_strip"
    return "line_strip"

def predict_from_bgr(img_bgr, line_model, dot_model):
    strip_type = detect_strip_type_rule_based_from_bgr(img_bgr)

    if strip_type == "line_strip":
        features = extract_line_strip_features_from_bgr(img_bgr)
        pred = line_model.predict(features)[0]
        proba = line_model.predict_proba(features)[0]
    else:
        features = extract_dot_strip_features_from_bgr(img_bgr)
        pred = dot_model.predict(features)[0]
        proba = dot_model.predict_proba(features)[0]

    label_map = {0: "normal", 1: "abnormal"}

    return {
        "strip_type": strip_type,
        "prediction": label_map[pred],
        "prob_normal": float(proba[0]),
        "prob_abnormal": float(proba[1]),
    }