# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pxvZcBnKaoQiPKzNGT4JP2ubA5IkWlMv
"""

import streamlit as st
import numpy as np
import cv2
from PIL import Image

from inference import load_models, predict_from_bgr

st.set_page_config(page_title="Paper Strip Classifier", page_icon="🧪")

st.title("Paper Strip Classifier")
st.write("Upload a paper-strip image to detect the strip type and classify it as normal or abnormal.")

@st.cache_resource
def get_models():
    return load_models()

line_model, dot_model = get_models()

uploaded_file = st.file_uploader(
    "Upload an image",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:
    pil_img = Image.open(uploaded_file).convert("RGB")
    st.image(pil_img, caption="Uploaded image", use_container_width=True)

    img_rgb = np.array(pil_img)
    img_bgr = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2BGR)

    result = predict_from_bgr(img_bgr, line_model, dot_model)

    st.subheader("Result")
    st.write(f"**Detected strip type:** {result['strip_type']}")
    st.write(f"**Prediction:** {result['prediction']}")
    st.write(f"**Normal probability:** {result['prob_normal']:.4f}")
    st.write(f"**Abnormal probability:** {result['prob_abnormal']:.4f}")